name: Build, Test & Deploy Demo

on:
  #repository_dispatch:
  workflow_dispatch:

  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

env:
  VERSION: 1.0.${{ github.run_number }}
  GITHUB_SHA: ${{ github.sha }}
  NEXT_TELEMETRY_DISABLED: 1
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}

jobs:
  lab:
    name: Build & Deploy to lab
    runs-on: ubuntu-latest
    environment: lab
    concurrency: lab
    env:
      ENV: lab

    steps:
      - uses: actions/checkout@v2
      
      - name: GCloud Auth with JSON
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY_LAB }}

      - name: Gcloud Auth with Token
        id: auth-lab
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_LAB }}
          service_account: ${{ secrets.GCP_DEPLOY_SERVICE_ACCOUNT_LAB }}
          token_format: 'access_token'
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build Docker image and manifest
        run: |
          sh ./ci/build.sh

      - name: Store build manifest
        uses: actions/upload-artifact@v1
        with:
          name: build.manifest
          path: ci/build.manifest
      
      - name: Publish and Deploy to Lab
        run: |
          sh ./ci/publish-and-deploy.sh web-lab
        env:
          GCP_REPOSITORY_NAME: web-lab